### ISSUE TITLE
largeMessage test fails on chrome

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js-env-selenium#105]

**Comment by gzm0** [comment]
It seems that chrome does not handle messages containing `0x7F` :shrug: It seems to alter them somehow. I still need to find out the details.

**Comment by gzm0** [comment]
Seems it simply drops these characters. Minimum reproducible example: https://github.com/gzm0/chrome-webdriver-js-string

**Comment by gzm0** [comment]
Filed as https://bugs.chromium.org/p/chromedriver/issues/detail?id=3672

**Comment by sjrd** [comment]
Wow, nice investigation!

**Comment by sbrunk** [comment]
Interesting. Perhaps some INT8/UINT8 issues then.

**Comment by gzm0** [comment]
So just FTR: My preference would be to have this issue solved on the chromedriver end. If necessary, we can work around it by encoding things differently when passing them back from the browser (this workaround would affect all browser types though).

There is currently no workaround that can be applied by users only.

**Comment by sbrunk** [comment]
I've switched the tests causing #119 to Firefox which is working fine. So I guess we can wait until this is fixed in chromedriver.
