### ISSUE TITLE
Too many browers being opened

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-env-selenium#15]
If I run a single test using `test-only`, even if `parallelExecution in Test` is `false`, a broswer pops-up-and-disappears 4 times. I would expect for a single test it should only happen once. Looking through the console when `keepAlive` is on, only the 4th and final window contains the actual test execution.

**Comment by sjrd** [comment]
That's actually normal. It has to do with the complicated logic needed to reproduce the entire sbt experience regarding testing.

**Comment by nicolasstucki** [comment]
We could investigate the possibility of closing the windows that are not involved in tests regardless of the `keepAlive` flag.

**Comment by japgolly** [comment]
> That's actually normal. It has to do with the complicated logic needed to reproduce the entire sbt experience regarding testing.

Can any part of the result of the logic be cached in SBT? Eg. have a `SettingKey[Option[X]]`, when `None` open browser 3 times, store result as `Some[X]`, subsequent invocations reuse; doing `clean` (or whatever) clears the setting and invalidates cache. Is that something that would be feasible and helpful?

> We could investigate the possibility of closing the windows that are not involved in tests regardless of the `keepAlive` flag.

Sounds like a good idea to me :+1:

**Comment by nicolasstucki** [comment]
#30 fixes:

> We could investigate the possibility of closing the windows that are not involved in tests regardless of the keepAlive flag.
