### ISSUE TITLE
Lots of stale builds on Travis

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js-env-selenium#35]
Example: https://travis-ci.org/scala-js/scala-js-env-selenium/jobs/122234714

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

I've seen quite a few today.

**Comment by japgolly** [comment]
FYI if the builds are legitimately taking 10+ min, you can prefix commands with `travis_wait [<time in min>]` so `travis_wait sbt` will wait 20min, `travis_wait 30 sbt` will wait 30min. Likely not what you want here but just in case it might be helpful.

**Comment by nicolasstucki** [comment]
It looks like it is always failing on the `keepAlive` tests. Currently we are not killing the browser instances at any time, this might be the source of the problem. I will improve this by killing them in between tests.
