### ISSUE TITLE
Option to configure protocol while running tests

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js-env-selenium#57]
Currently scala-js-selenium opening the following url in browsers : file:/var/folders/n0/c0fyqlqx0gg15mv4t5mchgj80000gn/T/1464125278337-0/scalajsRun.html

is it possible to configure prefix ? for local browsers i want to use  `file:`  and for remote browsers i want to  use  `http://local` or ...

**Comment by sjrd** [comment]
See #21

**Comment by chandu0101** [comment]
thank you :)
