### ISSUE TITLE
W3C WebDriver spec lacks log interface; test errors in latest geckodriver

### ISSUE THREAD

**Issue by godenji** [scala-js/scala-js-env-selenium#64]
[Geckodriver maintainer's response](https://github.com/mozilla/geckodriver/issues/330#issuecomment-259763286).

Only solution for now seems to be `@Ignore`ing affected tests (`timeoutSingleArgTest`, `utf8Test`, and `allowScriptTags`) in [SeleniumJSEnvFirefoxTest](https://github.com/scala-js/scala-js-env-selenium/blob/master/seleniumJSEnvKitTest/src/test/scala/org/scalajs/jsenv/selenium/firefox/SeleniumJSEnvFirefoxTest.scala) as they depend on [`hasOutput`](https://github.com/scala-js/scala-js/blob/master/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/JSEnvTest.scala#L20) method, which attempts to reference non-existent log implementation.

**Comment by gzm0** [comment]
Fixed in 005c3d2d3900b3748824f79a784540998fcf411a
