### ISSUE TITLE
Firefox is pinned to 54.0.1 on master

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js-env-selenium#83]
> JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]

Note that geckodriver is at the latest version. So I'm unsure why this happens.

**Comment by gzm0** [comment]
Most likely due to the new firefox version used (54.0.1 -> 55.0)

**Comment by sjrd** [comment]
How do people doing "serious stuff" with Selenium ever get anything done!? It seems the drivers regularly break :-(

**Comment by gzm0** [comment]
The master build now passes again. The latest-firefox branch monitors what happens when we use the latest firefox version (currently 55.0). I'm leaving this open so we don't forget to un-pin.

**Comment by sjrd** [comment]
Probably relevant doc: https://developer.mozilla.org/en-US/Firefox/Headless_mode
Headless support in FF 55.
